# site settings
title: Architectural Pancakces
subtitle:
email: nitika.duggal@architecturalpancakes.space
email_sub: nitikaduggal.arch@gmail.com
description: Something kewl
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://architecturalpancakes.space" # the base hostname & protocol for your site
author:
street_address:
city: Sydney
state:
zip_code:
country: Australia
phone: +61 450 919 305

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/architectural_pancakes/
linkedin_url: https://www.linkedin.com/in/nitikaduggal/
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
