# site settings
title: Architectural Pancakces
subtitle: "Graduate Architect | Designer | Artist"
email: nitika.duggal@architecturalpancakes.space
email_sub: nitikaduggal.arch@gmail.com
description: "Website and architecture portfolio of Nitika Duggal"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://architecturalpancakes.space" # the base hostname & protocol for your site
author: Nitika Duggal
street_address:
city: Sydney
state:
zip_code:
country: Australia
phone: +61 451 122 204
google_analytics: UA-176735298-1

# Collection settings
collections:
  photos:
  projects:
    output: true

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/architectural_pancakes/
linkedin_url: https://www.linkedin.com/in/nitikaduggal/
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
